global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "my-project"

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - "tasks.cadvisor"
        type: "A"
        port: 8080

  - job_name: "node-exporter"
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - "tasks.node-exporter"
        type: "A"
        port: 9100

  - job_name: "docker-registry"
    scrape_interval: 10s
    static_configs:
      - targets: ["registry.address:5001"]

  - job_name: "pihole"
    static_configs:
      - targets: ["pihole:9617"]

  - job_name: minio
    metrics_path: /minio/prometheus/metrics
    scrape_interval: 10s
    scheme: http
    static_configs:
      - targets:
          [
            "minio.address:9002",
            "minio.address:9003",
            "minio.address:9004",
            "minio.address:9005",
          ]

  - job_name: "mikrotik"
    scrape_interval: 5s
    scheme: http
    static_configs:
      - targets: ["mikrotik.address:9436"]

  - job_name: "traefik"
    scrape_interval: 5s
    scheme: http
    static_configs:
      - targets: ["traefik.localhost"]
